### ISSUE TITLE
Does not work for https

### ISSUE THREAD

**Issue by cmbirnbaum** [NullSoldier/ChromeMSDN#1]
The manifest permissions should be changed from "http://msdn.microsoft.com/*" to "_://msdn.microsoft.com/_".

**Comment by cmbirnbaum** [comment]
"*://msdn.microsoft.com/*"

**Comment by NullSoldier** [comment]
Thanks, I'll make the update and release a new version.

**Comment by NullSoldier** [comment]
I know it's been a long time, but I finally got around to uploading that update with the fix. I'm just clearing out my email now. This is now fixed.
